### ISSUE TITLE
Where is the code for detection and segmentation on Pascol Voc?

### ISSUE THREAD

**Issue by linzhiqiu** [facebookresearch/deepcluster#10]

**Comment by mathildecaron31** [comment]
Hi linzhiqiu,
Here are the code for [detection](https://github.com/rbgirshick/py-faster-rcnn) and [segmentation](https://github.com/shelhamer/fcn.berkeleyvision.org) on Pascal VOC.
Thanks for raising this issue, we are planning to release our prototxts specific to detection and segmentation for completeness.

**Comment by linzhiqiu** [comment]
Just wondering - when will the prototext be released?

**Comment by dedoogong** [comment]
I understood that it can cluster ImageNet data into 10000 cIasses. 
But I wonder that it also can cluster the bounding box of object or segmentation area. Does it need a separate object detector or segmentor(like pyfast/er rcnn or  mask rcnn) for capturing the right boxes or seg-area which are input to deepcluster? 
If so, should I run the detector/sementor first to get the object box or area and then run deep cluster with the result?

Please let me know some hint~!

Thank you.

**Comment by divamgupta** [comment]
@mathildecaron31 any updates?

**Comment by Chen-Song** [comment]
@mathildecaron31 Hi, would you share this prototxts used in your code?
