### ISSUE TITLE
Confused about the args.fc6_8 flag in eval_voc_classify.py

### ISSUE THREAD

**Issue by linzhiqiu** [facebookresearch/deepcluster#16]
I thought the flag fc6_8 is used to determine whether or not to fine-tune the entire model or just the final classifier. However, I don't understand why when fc6_8 is set to False, the model.feature will be randomly initialized? 

```
if not args.fc6_8:
        for y, m in enumerate(model.features.modules()):
            if isinstance(m, nn.Conv2d):
                n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                for i in range(m.out_channels):
                    m.weight.data[i].normal_(0, math.sqrt(2. / n))
                if m.bias is not None:
                    m.bias.data.zero_()
```

**Comment by mathildecaron31** [comment]
Hi linzhiqiu,
Thanks for pointing that out ! It's a bug indeed, the conv layers shouldn't be re-initialized. I didn't notice it because I always use the setting when I train only the MLP.
