### ISSUE TITLE
How do you convert a PyTorch model to Caffe model?

### ISSUE THREAD

**Issue by linzhiqiu** [facebookresearch/deepcluster#17]
A silly question: In order to use the Faster RCNN lib, it seems you need to generate the ".caffemodel" and the ".prototext" file for a given PyTorch model. Why is that part of the script not included in this repo?

**Comment by mathildecaron31** [comment]
I used this library to make the conversion:
https://github.com/marvis/pytorch-caffe-darknet-convert/blob/master/pytorch2caffe.py

**Comment by kongjibai** [comment]
> I used this library to make the conversion:
> https://github.com/marvis/pytorch-caffe-darknet-convert/blob/master/pytorch2caffe.py

404?
