### ISSUE TITLE
Time for validating

### ISSUE THREAD

**Issue by pvskand** [facebookresearch/deepcluster#18]
Hi there. Could you mention the time taken for the validation step (the one where you train mlp on imagenet data) with only `conv1` freezed features on Pascal P100?

**Comment by pvskand** [comment]
@mathildecaron31 could you answer the above query?

**Comment by mathildecaron31** [comment]
Hi,
During the validation step, no gradient is computed. Hence, this step is the same regardless of which parameters are freezed.

I don't get what experiment precisely you are referring to. Is it:
1- Re-training the MLP on ImageNet classification task, all conv parameters freezed (experiment of the supplementary material);
2- Training a linear classifier on ImageNet classification task on top of conv1 features ?

**Comment by pvskand** [comment]
Hi, 
I'll rephrase my question. By validation I meant the validation of the model trained in unsupervised fashion (via clustering). So I wanted the time taken for convergence of 2 ( Training of linear classifier on conv1 features).

**Comment by pvskand** [comment]
@mathildecaron31 any updates on the aforementioned question?

**Comment by mathildecaron31** [comment]
Hi,
I ran 90 epochs for convergence; I don't have the log specifying the time taken precisely on hand so I'll need to re-run the experiment to be able to reply.

**Comment by mathildecaron31** [comment]
Hi,
I have finally reproduced the experiment:
it takes 130 sec per training epoch and it takes 50 epochs to converge to a final precision (central crop) of 12.9 for conv1.
Thus this experiment on a single P100 gpu takes a total time of roughly 1h50.
