### ISSUE TITLE
prepare own image dataset

### ISSUE THREAD

**Issue by burnzzz** [facebookresearch/deepcluster#2]
Is there any documentation of how to prepare a dataset consisting of an folder of images for usage with deepcluster?

**Comment by burnzzz** [comment]
Ok, that was easy. Just make a train and a val subfolder and put all unlabeled data in val.

**Comment by Ehtii** [comment]
I would suggest to follow the train and val data sets in line with the original implementation. Make sure the sizes do match. It has been trained on color images, therefore customization will be needed for grayscale data.
