### ISSUE TITLE
Quesetion about principle of deepcluster

### ISSUE THREAD

**Issue by YoungJaeChoung** [facebookresearch/deepcluster#21]
I tried to use deepcluster on non-image and non-linear dataset, i.e. spiral data etc.

When I do pseudo class methods, it`s not obvious to me that how pseudo-class (which represents clustering results of k-means whose objective is a convex form) could be used to separate nonlinear data. 

Can I receive some hint for this question...?

**Comment by mathildecaron31** [comment]
Hi,
It is not clear to me what you mean by 'non-linear dataset'; I guess you mean non linearly separable.
Well in this case, we are in an unsupervised setting, so we don't really have access to labels. Thus, the notion of linearly separable is blurry in this setting. You'll always find pseudo-labels that make the problem linearly separable (each data represents its own class for example).

Pseudo-classes assignment is performed in the feature space (using the activations of the penultimate layer of the network) and not in the raw input space. In this space, the data are more likely to be separable.
As you say, k-means clustering produces an assignment of the data into clusters that are linearly separable (Voronoi diagram). The linear classifier (ie last layer of the network) then has to discriminate between different linearly separable pseudo-classes.

Hope it helps

**Comment by YoungJaeChoung** [comment]
Thank you for your answer. I mean non linearly separable data as you guessed.

My curiosity has been resolved :-)
