### ISSUE TITLE
Failed to reproduce the detection result using the AlexNet caffemodel provided

### ISSUE THREAD

**Issue by changliu816** [facebookresearch/deepcluster#23]
Hi, 

I am getting trouble with reproducing VOC detection result.

I used your pretrained caffe model AlexNet-prototxt + AlexNet-caffemodel and I finetune your model under Fast-RCNN framework from https://github.com/rbgirshick/py-faster-rcnn. 

To be specifically, I trained the Fast RCNN with the following script. All parameters were all set as default. 

./tools/train_net.py --gpu ${GPU_ID} \
  --solver models/${PT_DIR}/${NET}/fast_rcnn/solver.prototxt \
  --weights data/imagenet_models/yourmodel.caffemodel \
  --imdb ${TRAIN_IMDB} \
  --iters ${ITERS} \
  ${EXTRA_ARGS}

I could get 60.26 Mean AP with default ZF.v2.caffemodel, but it failed to converge when using your pre-trained model. The pre-trained weight is nearly close to noise initiation such that I cannot obtain any testing performance (MAP). The testing code returned me following error, which means the trained detector cannot detect anything. 

   BB = BB[sorted_ind, :]
IndexError: too many indices for array

I tested your caffemodel for VOC classification, and return a comparable result. But when coming to detection, it seemed not working.

I think I definitely made mistake at some point, or missed some processing procedure. Could you please tell me how you fine-tuned the Fast RCNN?  Did you modified any hyper parameters or  train.prototxt/  test.prototxt file? I read other self-supervised paper that did batch norm absorbance or weight rescaling from https://github.com/philkr/magic_init. I tested both scenario with or without post-processing techniques for detection, but failed in both case. 

Pascal evaluation really frustrated me for the past two weeks. I appreciate it if you could share me some insight. 

Best,
Chang

**Comment by piotr-bojanowski** [comment]
Hi Chang, 

The solver I used looked like:

```
base_lr: 0.002
lr_policy: \"step\"
gamma: 0.1
stepsize: 75000
display: 20
average_loss: 100
momentum: 0.9
weight_decay: 1e-3
snapshot: 9999999
```

I launched learning with: 

```
python ${TRAIN_SCRIPT} \\
  --solver ${JDIR}/solver.prototxt \\
  --weights ${MODEL} \\
  --imdb ${TRAIN_IMDB} \\
  --iters 150000 \\
  --cfg ${JDIR}/multiscale.yml \\
  --set EXP_DIR ${JDIR} DATA_DIR ${DATA} ROOT_DIR ${JDIR}
```

with the multiscale.yml as follows:

```
EXP_DIR: multiscale
TRAIN:
  SCALES: !!python/tuple [480, 576, 688, 864, 1200]
  MAX_SIZE: 2000
  SNAPSHOT_INFIX: multiscale
TEST:
  SCALES: !!python/tuple [480, 576, 688, 864, 1200]
  MAX_SIZE: 2000
```

I hope that helps.

Best,

Piotr Bojanowski

**Comment by divamgupta** [comment]
@piotr-bojanowski  @changliu816 Could you share the training model prototxt?
It would be extremely helpful

Thank you
