### ISSUE TITLE
Extracted features

### ISSUE THREAD

**Issue by bkj** [facebookresearch/deepcluster#24]
Is it possible to release the features extracted w/ the trained model for Imagenet?  I want to do a quick experiment, and this would save me from downloading Imagenet, running it through the model, etc.

Thanks!

**Comment by mathildecaron31** [comment]
Hi,
Thanks for your interest and sorry for the delay. I have released the ImageNet features for AlexNet and VGG16 models at the penultimate layer. Let me know if you need features at a particular layer.
