### ISSUE TITLE
how to get clustering result of origin file name through data in file "/exp/clusters" ？

### ISSUE THREAD

**Issue by SpartacusIn21** [facebookresearch/deepcluster#25]

**Comment by mathildecaron31** [comment]
Hi,
You may load the list of cluster assignments with pickle as it was [saved](https://github.com/facebookresearch/deepcluster/blob/dc2d659c9a40df41640575bbaac11656bb52a251/util.py#L119) with pickle.
You can do the following: `cluster_assignments = pickle.load(open('/exp/clusters', 'rb'))`. This is a list, `cluster_assignments[0]` will give you the cluster assignment for the whole dataset at epoch 0.

**Comment by cptbtptp125** [comment]
Can the results of cluster assignment be visualized directly? That is, the classification result image is directly saved into the corresponding category folder.
