### ISSUE TITLE
CUDA error 35 CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by enjoy4** [facebookresearch/deepcluster#28]
when i use my dataset train the model,i came cross the error

Faiss assertion 'err__ == cudaSuccess' failed in int faiss::gpu::getNumDevices() at gpu/utils/DeviceUtils.cu:32; details: CUDA error 35 CUDA driver version is insufficient for CUDA runtime version

but when i try the error code 
>>> index = faiss.GpuIndexFlatL2(res,256)
>>> flat_config = faiss.GpuIndexFlatConfig()
>>> flat_config.useFloat16 = False
>>> flat_config.device = 0
>>> index = faiss.GpuIndexFlatL2(res,256,flat_config)
>>> 
it'right

the error code 
    res = faiss.StandardGpuResources()
    flat_config = faiss.GpuIndexFlatConfig()
    flat_config.useFloat16 = False
    flat_config.device = 0
    index = faiss.GpuIndexFlatL2(res, d, flat_config)

**Comment by mathildecaron31** [comment]
Hi, reading your error message I think you need to update your GPU driver.
Please see https://github.com/facebookresearch/faiss for help with faiss library.
