### ISSUE TITLE
could you provide more details about the imagenet data used

### ISSUE THREAD

**Issue by MozarTuring** [facebookresearch/deepcluster#29]

**Comment by mathildecaron31** [comment]
Hi,
I used the entire train set of ImageNet (1281167 images). I obviously do not take the labels into account for training deepcluster.
Hope that helps.

**Comment by chester-w-xie** [comment]
In your code, the value of NMI is calculated using the cluster labels generated by the two iterations, unlike in most articles, which use the predicted labels with the true labels to calculate NMI and several other metrics. I tried to modify your code to adopt the latter approach for the NMI calculation and found that the results became worse.
