### ISSUE TITLE
cluster labels

### ISSUE THREAD

**Issue by sj31867** [facebookresearch/deepcluster#33]
Hi Iam running the unsupervised training. The clusters assignment that is saved is a list of list of list where each image is assigned an index. how do i map that index to image file?

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest,
[images_lists](https://github.com/facebookresearch/deepcluster/blob/dc2d659c9a40df41640575bbaac11656bb52a251/main.py#L207) is a list of list. Each element of the list is a list of image indexes belonging to this cluster. The image indexes correspond to the ones defined in the [dataset](https://github.com/facebookresearch/deepcluster/blob/dc2d659c9a40df41640575bbaac11656bb52a251/main.py#L130).
Hope that helps
