### ISSUE TITLE
Does the dimension of PCA dimensionality reduction after extracting features have an effect on the results?

### ISSUE THREAD

**Issue by 106224** [facebookresearch/deepcluster#50]
Does the dimension of PCA dimensionality reduction after extracting features have an effect on the results?

**Comment by mathildecaron31** [comment]
Hi, you can explore this by running deepcluster training with different dimension for the features. My intuition is that it doesn't have a big impact as long as you use enough dimension to retain most of the variance.

**Comment by 106224** [comment]
> Hi, you can explore this by running deepcluster training with different dimension for the features. My intuition is that it doesn't have a big impact as long as you use enough dimension to retain most of the variance.

Thank you for your reply
