### ISSUE TITLE
CPU or other CUDA versions supported?

### ISSUE THREAD

**Issue by khg2478** [facebookresearch/deepcluster#51]
Hi. Due to hardware dependency, I cannot really use this library. I tried to set caffe in CPU mode and tried to run it but I face other issues.

Is there any other ways to run in CPU or other CUDA compatible modes?

Thanks.

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest.
This library uses PyTorch, not Caffe. We do not provide CPU mode only unfortunately.
Sorry for the inconvenience
