### ISSUE TITLE
i have question about eval-linear.sh?

### ISSUE THREAD

**Issue by 106224** [facebookresearch/deepcluster#53]
I want to ask when running eval-linear.sh, each epoch has an accuracy rate, but the accuracy rate of each epoch is different, and there are even large differences. Which accuracy rate should I choose?thanks

**Comment by 106224** [comment]
In other words, which one of [top1.val, top1.avg, best_prec1] did you choose in your paper?

**Comment by mathildecaron31** [comment]
Hi, I selected best_prec1 for the reported accuracy
