### ISSUE TITLE
Some question about NMI.

### ISSUE THREAD

**Issue by 106224** [facebookresearch/deepcluster#54]
In my experiments, I'm confused about my NMI value did not tend to a certain value, but it kept fluctuating and was irregular.

**Comment by mathildecaron31** [comment]
Do you mean the NMI with the ground truth labels or between two consecutive clusterings ?
Also could you provide some specifics about your experiments ? dataset, nmb of clusters, etc ?

**Comment by 106224** [comment]
I think I have solved this problem, the reason is that the setting of K is too small, and I have another question, how do I measure NMI with the ground truth labels, can you give specific code?

**Comment by 106224** [comment]
how do I measure NMI with the ground truth labels, can you give specific code?
### `nmi = normalized_mutual_info_score(
                    clustering.arrange_clustering(deepcluster.images_lists),
                    clustering.arrange_clustering(cluster_log.data[-1])
                )`

**Comment by mathildecaron31** [comment]
Hi, happy to hear that you solve your problem. For the NMI with ground truth labels you can measure the NMI between two assignments A and B with `normalized_mutual_info_score(A, B)`. `A` may correspond to a list with the size of the dataset where each entry `A[i]` corresponds to the cluster id the data point `i` belongs to. `B` may correspond to a list with the size of the dataset where each entry `B[i]` corresponds to the ground truth label of data point `i`.
