### ISSUE TITLE
vgg16 out of memory(can't solve)

### ISSUE THREAD

**Issue by HellFireC02** [facebookresearch/deepcluster#55]
Excuse me, i have a trouble about your vgg16 model.
I want to use your pretrained model(vgg16) to run my dataset.
But when I run my code  using gtx1060 it shows 'out of memory'.Here is the log:

**Architecture: vgg16
=> loading checkpoint '/home/sky/deepcluster_models/vgg16/checkpoint.pth.tar'
Loaded
Load dataset: 0.01 s
Compute features
Traceback (most recent call last):
  File "main_2_vgg.py", line 349, in <module>
    main()
  File "main_2_vgg.py", line 164, in main
    features = compute_features(dataloader, model, len(dataset))
  File "main_2_vgg.py", line 326, in compute_features
    aux = model(input_var).data.cpu().numpy()
......
RuntimeError: CUDA out of memory. Tried to allocate 3.06 GiB (GPU 0; 5.94 GiB total capacity; 3.45 GiB already allocated; 1.50 GiB free; 217.01 MiB cached)**

In theory, if I modify the size of the batch, this problem can be solved, so I made some modifications to main.sh as follows:
**...
ARCH="vgg16"
LR=0.05
WD=-5
K=4
WORKERS=4
BATCH=5(previous value was 20)
CHECKPOINTS=10
EXP="/home/${USER}/test/task01_vgg16_pytorch"
PYTHON="${HOME}/anaconda2/bin/python"
...**
but the problem still exists,  and the memory used does not seem to be reduced as a result.
Even the logs are almost the same (I suspect the batch-size cannot address this issue):

**Architecture: vgg16
=> loading checkpoint '/home/sky/deepcluster_models/vgg16/checkpoint.pth.tar'
Loaded
Load dataset: 0.02 s
Compute features
Traceback (most recent call last):
  File "main_2_vgg.py", line 349, in <module>
    main()
  File "main_2_vgg.py", line 164, in main
    features = compute_features(dataloader, model, len(dataset))
  File "main_2_vgg.py", line 326, in compute_features
    aux = model(input_var).data.cpu().numpy()
RuntimeError: CUDA out of memory. Tried to allocate 3.06 GiB (GPU 0; 5.94 GiB total capacity; 3.45 GiB already allocated; 1.50 GiB free; 217.01 MiB cached)**

By the way, I successfully ran your code using the Alexnet pre-trained model you provided, so this problem is only related to memory, but I can't find a solution.
I hope you can give me some help. Thanks a lot!

**Comment by mathildecaron31** [comment]
Hi,
The only way I see to reduce your memory usage on GPU is indeed to reduce the batch size. Have you tried running with `--batch 1`? If it doesn't work then I don't think you can use this code with your current hardware :(

**Comment by HellFireC02** [comment]
after changing batch to 1, it still doesn't work :( 
i notice that your pretrained model Alexnet use the image whose size is 224*224.
and your pretrained model Vgg use use the image whose size is 64*64.

so i used the torchsummary to test the parameter scale of those two networks.
it shows the alexnet is : 

**Total params: 99,242,504
Trainable params: 99,242,480
Non-trainable params: 24

Input size (MB): 0.57
Forward/backward pass size (MB): 17.26
Params size (MB): 378.58
Estimated Total Size (MB): 396.42**

and VGG16 is : 

**Total params: 80,866,600
Trainable params: 80,866,576
Non-trainable params: 24

Input size (MB): 0.05
Forward/backward pass size (MB): 26.59
Params size (MB): 308.48
Estimated Total Size (MB): 335.12**

it shows  that they don't make much difference in memory usage.
but why the alexnet can work while vgg can't ?

i notice the error is mainly related to this line of code: 
**output = model(input_var)**

and the memory warining even doesn't change:
**RuntimeError: CUDA out of memory. Tried to allocate 3.06 GiB (GPU 0; 5.94 GiB total capacity; 3.45 GiB already allocated; 1.47 GiB free; 207.70 MiB cached)**

if i don't upgrade my hardware in a short time, is there any way I can use the vgg model? (even if it will cause some performance loss)

**Comment by mathildecaron31** [comment]
Hi, both AlexNet and VGG-16 models take as input images of 224*224 resolutions.
