### ISSUE TITLE
What is the purpose for removing the fc layer on each epoch?

### ISSUE THREAD

**Issue by dreamy-viator** [facebookresearch/deepcluster#59]
https://github.com/facebookresearch/deepcluster/blob/master/main.py#L145

I'm confused why you're removing the head on each epoch.
Can you explain plz?

Thank you.

**Comment by mathildecaron31** [comment]
Hi, the goal is to re-set the last fully connected layer whenever the clusters are re-assigned. Indeed, when there is a re-assignment, the pseudo-classes change completely and the top layer becomes outdated. Hope it helps
