### ISSUE TITLE
Training dataset contains both train and test images

### ISSUE THREAD

**Issue by amajee11us** [facebookresearch/deepcluster#60]
Hi.. Great Work !! 
I was wondering if the data used for training the deepcluster pseudo-labels use both the train and test images? 
If so how would be the folder structure for the dataset?

**Comment by mathildecaron31** [comment]
Hi, thank you for your interest in our work !
We use only images from the train split of ImageNet in our training. But you can choose to train the model on any data you want.
Hope it helps.
