### ISSUE TITLE
pre-trained model error

### ISSUE THREAD

**Issue by S-alhammad** [facebookresearch/deepcluster#61]
hi there,
when trying to run the pretrained model an error occurs.
`optimizer.load_state_dict(checkpoint['optimizer']) 
KeyError: 'optimizer'`

When checking the keys of checkpoint, there is no key named optimizer. 
`'ckeckpoint.keys', ['arch','epoch','state_dict']`

Thank you

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest in my code !
Yes, I indeed removed the optimizer state_dict from the released checkpoint as it is not very informative...
You can simply skip with line of code when loading the checkpoint, either by commenting the line or with a `try` statement for example
