### ISSUE TITLE
Using seperate optimizer for annexed top layer.

### ISSUE THREAD

**Issue by AhmadM-DL** [facebookresearch/deepcluster#62]
Hello there,

I saw that you are using two optimizers for Deep Cluster. One for the entire network except the top layer and one for the annexed top layer every cycle.
```
    # create an optimizer for the last fc layer
    optimizer_tl = torch.optim.SGD(
        model.top_layer.parameters(),
        lr=args.lr,
        weight_decay=10**args.wd,
    )
```
@mathildecaron31 
Wouldn't it be better to use a single optimizer with different param_groups?
As in [Pytorch Docs](https://pytorch.org/docs/stable/optim.html#per-parameter-options)?

**Comment by mathildecaron31** [comment]
Yes, you can definitely do that :)
