### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by AhmadM-DL** [facebookresearch/deepcluster#63]
Hello there,

In your paper, you wrote that you have used (random horizontal flips + random crops).
However, this is not reflected in your code.
Am I missing something?

Thank you.

**Comment by mathildecaron31** [comment]
Hi,
Thanks for your interest in our work :). The data augmentation is here: https://github.com/facebookresearch/deepcluster/blob/9796a71abbfd14181a2b117d6244e60c2d94efbf/clustering.py#L140-L145
