### ISSUE TITLE
Support for latest pytorch

### ISSUE THREAD

**Issue by thenamangoyal** [facebookresearch/deepcluster#65]
Can the code be modified to support latest versions
Pytorch >=1.5.0
Python >=3.5
CUDA >=10.1

As Installing CUDA 8.0 would lead to breaking of all machines.

**Comment by mathildecaron31** [comment]
Hi, unfortunately I am not planning to update the code (well maybe during the summer if I have some spare time who knows ^^). However it should not be too difficult to adapt it yourself since the codebase is fairly simple.
Thanks for your interest,
Mathilde
