### ISSUE TITLE
Train on a smaller dataset

### ISSUE THREAD

**Issue by saramsv** [facebookresearch/deepcluster#66]
Hi, thank you for the wonderful work! 
I was wondering if you could provide some information about the format of the input files and datasets. I am trying to run the code and then use it on my dataset, however, imagenet is very large and I cannot download it. Do you have any suggestions on a smaller dataset and its format for testing purposes?

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest in this work. The method and the code are not dataset specific so you should be able to adapt it for your own dataset. You can use your own dataset class here for example: https://github.com/facebookresearch/deepcluster/blob/9796a71abbfd14181a2b117d6244e60c2d94efbf/main.py#L129
Hope that helps, feel free to re-open the issue if not or if you have further questions
