### ISSUE TITLE
Will the code of  deep-cluster-v2 in "Unsupervised Learning of Visual Features by Contrasting Cluster Assignments" be released in this repository?

### ISSUE THREAD

**Issue by haohang96** [facebookresearch/deepcluster#67]

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest.
Yes, I'm planning to release DeepClusterv2 and SwAV implementations in this repository in one or two weeks. Stay tuned

**Comment by haohang96** [comment]
A few more quesitons about deep-cluster v2:

1. If MLP projection head is also used in deep-cluster v2?

2. If MLP is used,  is $z$ in eq8 (eq8 in SWaV paper) the normalized vector of mlp layer's output?

**Comment by mathildecaron31** [comment]
Hi,
I've just released our implementation at https://github.com/facebookresearch/swav

1. Yes
2. Yes
