### ISSUE TITLE
'Clustering' object has no attribute 'obj'

### ISSUE THREAD

**Issue by Alice-Shen** [facebookresearch/deepcluster#70]
`clus = faiss.Clustering(d, nmb_clusters)
clus.train(x, index)
losses = faiss.vector_to_array(clus.obj)`

I don't know why it's wrong,would you help me?

**Comment by boom85423** [comment]
Did you find the solution? I also suffer from the same problem

**Comment by Alice-Shen** [comment]
Yes,I have solved the problem.
`stats = clus.iteration_stats
obj = np.array([stats.at(i).obj for i in range(stats.size())])`
relace the 'losses = faiss.vector_to_array(clus.obj)'
