### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'weight'

### ISSUE THREAD

**Issue by hosea7456** [facebookresearch/deepcluster#73]
Hi, I am trying to run the DeepClusterNet of your code. But I have some problems with it.
When I run the train.py, it shows:

    fd = int(model.top_layer.weight.size()[1])
AttributeError: 'NoneType' object has no attribute 'weight'

I couldn't found the imformation about 'model.top_layer.weight'. How can I figure it out? Thank you.

**Comment by mathildecaron31** [comment]
Hi, thanks for your interest. Can you try printing the model (`print(model)`) just before you get the error ?

**Comment by hosea7456** [comment]
Hi , mathildecaron31, sorry for the lat reply . 
There is some problem with the models I downloaded . I try (print (model )) , It's showing None . 
So I remove the model's folder and redownload it . Finaly I solved this issue , Thank you!
