### ISSUE TITLE
AttributeError: 'Clustering' object has no attribute 'obj'

### ISSUE THREAD

**Issue by liupeng0606** [facebookresearch/deepcluster#76]
kmeans = faiss.Clustering(d, num_clusters)

 kmeans.train(x, index)

objective = faiss.vector_float_to_array(kmeans.obj)

print error

AttributeError: 'Clustering' object has no attribute 'obj'

**Comment by daniiki** [comment]
same here, could you solve the issue?

**Comment by daniiki** [comment]
So I could solve the problem doing some research:
In clustering.py you have to delete this line: 
`losses = faiss.vector_to_array(clus.obj)` in function run_kmeans
and replace it with the following lines:
`stats = clus.iteration_stats`
`losses = np.array([stats.at(i).obj for i in range(stats.size())])`

**Comment by mathildecaron31** [comment]
Glad to see that you solved the issue. I think it happens because I was using a previous version of faiss at the time of this work.
