### ISSUE TITLE
Question: Can I use the model to cluster unlabelled texts?

### ISSUE THREAD

**Issue by basque21** [facebookresearch/deepcluster#8]
Hi, I'ts not an issue but a question. I want to make clusters of texts of different topics, which are unlabelled. Say I have notices about sport, economy and politics, would it be possible to train the DeepCluster for making this 3 clusters without any labelled text?
Thanks for your work!

**Comment by mathildecaron31** [comment]
Hi,
Thanks for your interest. Yes, you can adapt this code to deal with text input instead of images. Keep in mind that data augmentation and a big amount of data are both crucial for our method to work well.
Good luck :)
Mathilde
