### ISSUE TITLE
Dealing with empty clusters

### ISSUE THREAD

**Issue by dkajtoch** [facebookresearch/deepcluster#87]
Hello, where exactly in the code do you deal with empty clusters? I couldn't spot that part

> when a cluster becomes empty, we randomly select a non-empty cluster and use its centroid with a small random perturbation as the new centroid for the empty cluster.

**Comment by mathildecaron31** [comment]
Hi @dkajtoch 

This is handled in faiss: https://github.com/facebookresearch/faiss/blob/b78e21aaab5ee6dd57c797c2665a3be89ba4f854/faiss/Clustering.cpp#L212-L218

**Comment by dkajtoch** [comment]
Thanks! This is exactly what I was looking for

**Comment by mathildecaron31** [comment]
you can also take a look at my implementation in pytorch for deepercluster:
https://github.com/facebookresearch/DeeperCluster/blob/d38ada109f8334f6ae4c84a218d79848a936ed6f/src/distributed_kmeans.py#L259-L279
