### ISSUE TITLE
why do we need at least 39 training points per cluster ?

### ISSUE THREAD

**Issue by hujiaodou96** [facebookresearch/deepcluster#9]
when  I trained on my own dataset, it raises the warning: clustering 14243 points to 810  centroids,please provide as least 31590 training points.So I guess per cluster class need 39 training points,so how to break the limit for the lack of training data? thanks

**Comment by mathildecaron31** [comment]
Hi,
Thanks for your interest.
First, this message is only a warning, it means the clustering will be performed even though you provide less than 39 * k datapoints. _faiss_ library is just warning you that the clustering quality would be better with more data.

For more information about how the k-means is implemented with _faiss_ library please look [here](https://github.com/facebookresearch/faiss/blob/master/Clustering.cpp)
